const LegacyProjectData = [
  {
    title: "Waste Fuel Market Analysis Tool",
    image: "",
    description: "Updated Profu’s Ulven tool to align with new emission fee rules in Sweden.",
    problem: "Adapted backend and database to support revised reception fee calculations and maintain stability.",
    skills: [".NET Framework 4.8", "C#", "Razor"],
    githubLink: "",
    githubReadme: "",
    youtubeLink: "",
  },
  {
    title: "Vehicle State Management Application",
    image: "",
    description: "Enhanced vehicle state filtering and added a changelog to track data changes for Volvo Penta.",
    problem: "Solved nested data model complexities and improved field validation and data sorting.",
    skills: ["React-admin", "MUI", "C#", ".NET"],
    githubLink: "",
    githubReadme: "",
    youtubeLink: "",
  },
  {
    title: "Heating Cost Comparison Platform",
    image: "",
    description: "Maintained and debugged Profu’s Fjärrkontrollen website for heating cost comparisons.",
    problem: "Fixed duplicated data issue, restructured graphs and layout for better accuracy, and updated a over-engineered algorithm.",
    skills: ["React", "ASP.NET", "Angular", "Azure", "Swagger"],
    githubLink: "",
    githubReadme: "",
    youtubeLink: "",
  },
  {
    title: "Educational Reading Web Platform",
    image: "",
    description: "Upgraded Läskuppen's reading platform to improve navigation, layout, and scalability.",
    problem: "Enhanced database structure, added admin tools, and expanded API and search functionality.",
    skills: ["React", "SQL", "MUI", "C#", "JavaScript", "HTML", "CSS"],
    githubLink: "",
    githubReadme: "",
    youtubeLink: "",
  },
  {
    title: "Mobile Incident Reporting Application",
    image: "",
    description: "Developed a mobile app for incident reporting with automatic image-based description.",
    problem: "Integrated image analysis and user editing features into Boards On Fire's reporting system.",
    skills: ["React Native", "JavaScript", "Node.js"],
    githubLink: "",
    githubReadme: "",
    youtubeLink: "",
  },
];

export default LegacyProjectData;
